**Ineuron Python Basic Programming Assignment 8**

1. Write a Python Program to Add Two Matrices?


In [2]:
import numpy as np
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,8]])
mat2 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))

The Sum of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 8]]  and 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  is 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 17]] 


2. Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,8]])
mat2 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
mulMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,mulMat))

The product of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 8]]  and 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  is 

[[ 30  36  42]
 [ 66  81  96]
 [ 95 118 141]] 



3. Write a Python Program to Transpose a Matrix?

In [6]:
import numpy 
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,8]])
print(mat1)
print("\n")
print("Tnasposed matrix",numpy.transpose(mat1))

[[1 2 3]
 [4 5 6]
 [7 8 8]]


Tnasposed matrix [[1 4 7]
 [2 5 8]
 [3 6 8]]



4. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
input_string = input("Enter string")
words = input_string.split()
words.sort()
for word in words:
    print(word)

Enter stringmy name is ashish
ashish
is
my
name



5. Write a Python Program to Remove Punctuation From a String?

In [8]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
input_string = input("Enter a string with punctuations:")
rem_punc = ""
for i in input_string:
    if i not in punctuations:
        rem_punc = rem_punc + i
print(rem_punc)

Enter a string with punctuations:@shish is my name
shish is my name
